# Generated by Django 4.0.1 on 2022-01-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_email_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
