# Generated by Django 4.0.1 on 2022-01-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee',
            field=models.BooleanField(verbose_name='Employee'),
        ),
    ]
