# Generated by Django 4.0.1 on 2022-01-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employee',
        ),
    ]
